# ----------------------------------------------------------------------------
#
# DicomSel: DICOM Image Selector
#
# Copyright (C) 2005 IRCAD
# Authors: Benjamin Gaillard, Marc-Aurèle Mörk, Guillaume Spitz
#
# ----------------------------------------------------------------------------
#
# << LICENCE >>
#
# ----------------------------------------------------------------------------


TOPDIR   = ..$(DIRSEP)..
INCLUDES = -I..$(DIRSEP)include$(DIRSEP)dicom -I..$(DIRSEP)include
BIN      = libdicom.a
SRC      = $(wildcard *.cpp) $(wildcard *$(DIRSEP)*.cpp)

include ../../mkfiles/rules.mk

# End of File
